- name: Get GitHub Runner IP
  id: ip
  uses: haythem/public-ip@v1.3

- name: Whitelist Runner IP in AWS Security Group
  run: |
    aws ec2 authorize-security-group-ingress \
      --group-id ${{ secrets.AWS_SG_ID }} \
      --protocol tcp \
      --port 22 \
      --cidr ${{ steps.ip.outputs.ipv4 }}/32
  env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: ap-southeast-2

- name: Deploy via SSH
  uses: appleboy/ssh-action@v1.2.0
  with:
    host: ${{ secrets.HOST }}
    username: ${{ secrets.USERNAME }}
    key: ${{ secrets.KEY }}
    script: |
      cd ~/flask-ecommerce
      git pull origin main
      source venv/bin/activate
      pip install -r requirements.txt
      sudo systemctl restart flaskapp

- name: Revoke Runner IP from AWS Security Group
  if: always()
  run: |
    aws ec2 revoke-security-group-ingress \
      --group-id ${{ secrets.AWS_SG_ID }} \
      --protocol tcp \
      --port 22 \
      --cidr ${{ steps.ip.outputs.ipv4 }}/32
  env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: ap-southeast-2